server.port=9090
spring.application.name=courier_help
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
logging.charset.console=UTF-8
file.encoding=UTF-8
